version: '3.7'

services:
  workspide:
    build: ./
    restart: "always"
    hostname: workspide
    container_name: workspide
    ports: 
      - "8000:8000"
    env_file: 
      .envrc
    volumes:
      - ./django:/django
    entrypoint: ["sh", "-c"]
    command: ["python manage.py runserver 0.0.0.0:8000"]
    stdin_open: true
    tty: true
