# Generated by Django 2.2.6 on 2019-10-17 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UseUser',
        ),
    ]
