# Generated by Django 2.2.6 on 2019-10-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='experience_months',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='currency',
            field=models.CharField(choices=[('uah', 'uah'), ('usd', 'usd'), ('eur', 'eur')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(choices=[('uah', 'uah'), ('usd', 'usd'), ('eur', 'eur')], max_length=3, null=True),
        ),
    ]
