# Generated by Django 2.2.6 on 2019-10-30 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pide',
            name='state',
        ),
        migrations.AddField(
            model_name='pide',
            name='pub_dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
