# Generated by Django 2.2.6 on 2019-10-27 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ad',
            name='experience_type',
            field=models.CharField(choices=[('month', 'months'), ('year', 'years')], default='month', max_length=5),
        ),
    ]
