# Generated by Django 2.2.6 on 2019-10-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191030_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='pide',
            name='state',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('rejected', 'rejected')], default='pending', max_length=9),
        ),
    ]
