# Generated by Django 2.2.6 on 2019-10-30 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191030_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pide',
            name='uid_from',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='uid_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
