# Generated by Django 2.2.6 on 2019-10-27 22:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191027_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
