# Generated by Django 2.2.6 on 2019-10-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191027_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='date',
        ),
        migrations.AlterField(
            model_name='ad',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
