# Generated by Django 2.2.6 on 2019-10-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pide_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pide',
            name='state',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=8),
        ),
    ]
