# Generated by Django 2.2.6 on 2019-11-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191031_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
