# Generated by Django 2.2.6 on 2019-11-01 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ad_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pide',
            name='ad_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_from', to='main.Ad'),
        ),
        migrations.AlterField(
            model_name='pide',
            name='ad_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_to', to='main.Ad'),
        ),
    ]
