# Generated by Django 2.2.6 on 2019-11-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191101_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='experience_months',
            new_name='experience',
        ),
    ]
