# Generated by Django 2.2.6 on 2019-11-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191102_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='experience_type',
            field=models.CharField(choices=[('months', 'months'), ('years', 'years')], default='month', max_length=6),
        ),
    ]
