# Generated by Django 2.2.6 on 2019-11-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191103_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
